### ISSUE TITLE
autowried templateEngin in service

### ISSUE THREAD

**Issue by user20161119** [thymeleaf/thymeleafexamples-springmail#3]
I separate spring config files in src/main/resources/applicationContext.xml and WEB-INF/springmvc-servlet.xml

and i config template engin in springmvc-servlet.xml

``` java
<bean name="templateEngine" id="templateEngine" class="org.thymeleaf.spring3.SpringTemplateEngine">
        <property name="templateResolvers">
            <set>
                <ref bean="emailTemplateResolver" />
                <ref bean="webTemplateResolver" />
            </set>
        </property>
    </bean>
```

i want autowired the templateEngin in my @service bean,but get error:

``` java
can not find bean templateEngine
```

i googled and know i need to config templateEngin duplicate in src/main/resources/applicationContext.xml ,i want to know there is any other way reduce duplicate templateEngin Declaration? thanks

**Comment by jmiguelsamper** [comment]
Hello,

I don't fully understand your problem, but it seems a Spring configuration problem. I think you should reference springmvc-servlet.xml somewhere.

As far as the email tutorial is concerned, be aware that we use two different TemplateEngine in order to separate the rendering of the web application from the rendering of the emails. Only one TemplateEngine could be used, but I think the other way is clearer.

Regards,
   Zemi

**Comment by user20161119** [comment]
thanks,i configed SpringTemplateEngine combined with spring mvc(spring mvc servlet),but now,i config it in spring root file(applicationContext).it's work now.
